version: '3'
services:
  backend:
    build:
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./backend:/backend
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    tty: true

  frontend:
    build:
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./frontend/node:/usr/src/app/frontend
    command: sh -c "cd /usr/src/app/frontend && yarn start"
    ports:
      - "3000:3000"
